# Change these first
owner: Zekariaa # Your GitHub organization or username, where this repository lives
repo: Wilderia # The name of this repository

sites:
  - name: Site-web
    url: https://wilderia.fr
  - name: Proxy
    check: "tcp-ping"
    url: 185.157.247.55
    port: 10000
  - name: Survie
    check: "tcp-ping"
    url: 185.157.247.55
    port: 10001
  - name: Lobby
    check: "tcp-ping"
    url: 185.157.247.55
    port: 10002
  - name: Bases de données
    check: "tcp-ping"
    url: 185.157.247.55
    port: 10000
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: live.wilderia.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wilderia, en direct
  introTitle: "Surveillez l'état de nos serveurs de jeux **en direct**"
  introMessage: "Nos serveurs de jeux ne sont malheureusement pas parfaits et **peuvent subir des pannes**. Suivez-ici l'avancement de nos maintenances."
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://wilderia.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
